// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationPractice.Data;

namespace MigrationPractice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MigrationPractice.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "UZ",
                            Name = "Uzbekistan",
                            ShortName = "UZB"
                        },
                        new
                        {
                            Id = 2,
                            Language = "RU",
                            Name = "Russia",
                            ShortName = "RUS"
                        },
                        new
                        {
                            Id = 3,
                            Language = "EN",
                            Name = "England",
                            ShortName = "ENG"
                        });
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MAth group"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics group"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Informatics group"
                        });
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.HomeWork.GroupsTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherId");

                    b.ToTable("GroupsTeacher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 3,
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Internationa Uzb Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            Name = "SuperContinental",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            Name = "Internationa Uzb Hotel",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            FirstName = "Alijon",
                            GroupId = 1,
                            LastName = "Karimov"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            FirstName = "Javohir",
                            GroupId = 2,
                            LastName = "Jorayev"
                        },
                        new
                        {
                            Id = 3,
                            Age = 26,
                            FirstName = "Xurshid",
                            GroupId = 3,
                            LastName = "Torayev"
                        });
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Informatics",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teacher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNumber = "6800101023233003",
                            Experience = 20,
                            FullName = "Abdusattor Ortiqov"
                        },
                        new
                        {
                            Id = 2,
                            CardNumber = "6800101023235005",
                            Experience = 25,
                            FullName = "Sardor Komilov"
                        },
                        new
                        {
                            Id = 3,
                            CardNumber = "6800101023234004",
                            Experience = 28,
                            FullName = "Jahongir Aripov"
                        });
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.HomeWork.GroupsTeacher", b =>
                {
                    b.HasOne("MigrationPractice.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigrationPractice.Data.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Hotel", b =>
                {
                    b.HasOne("MigrationPractice.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Student", b =>
                {
                    b.HasOne("MigrationPractice.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MigrationPractice.Data.Models.Subject", b =>
                {
                    b.HasOne("MigrationPractice.Data.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
